apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/vic-goog-meli-demo/web-server
deploy:
  kubectl:
    manifests:
      - k8s-deployment.yaml
profiles:
  - name: deploy
    build:
      googleCloudBuild:
        projectId: vic-goog-meli-demo
